baseURL = "https://mansur.moscow/"
languageCode = "en-us"
title = "Mansur's Home for Projects and Experiments"
theme = "hestia-pure"

[author]
 author = 'Mansur Marvanov'
 profile = ' '

[Params]
 localOgp = 'en'
 description = " "
 twitter = "nanorobocop"
 github = "nanorobocop"
 linkedin = "https://www.linkedin.com/in/mansur-marvanov/"
 googleanalytics = "UA-124178050-1"
 yandexmetrika = 50001151
