baseURL = "https://mansur.moscow/"
languageCode = "en-us"
title = "Mansur's Home for Projects and Experiments"
theme = "hestia-pure"

[author]
 author = 'Mansur Marvanov'
 profile = ' '

[Params]
 image = "images/og.png"
 localOgp = 'en'
 description = " "
 twitter = "nanorobocop"
 github = "nanorobocop"
 linkedin = "https://www.linkedin.com/in/mansur-marvanov/"
 googleanalytics = "UA-124178050-1"
 yandexmetrika = 50001151
 links = [ "https://ci.mansur.moscow", "https://mon.mansur.moscow", "http://mansur6rabj6sixa.onion/", "https://мансур.москва", "https://test-driven.ru" ]
